name: "Fetch Emby releases"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * */2' # Every 2nd day at 03:00
jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Emby releases
        run: | 
          EMBY_VERSION=`gh api /repos/MediaBrowser/Emby.Releases/releases/latest -q .tag_name`
          echo $EMBY_VERSION
          # Set environment variable
          echo "EMBY_VERSION=$EMBY_VERSION" >> $GITHUB_ENV
      - name: Replace application.version with emby version in app.properties
        run: sed -i "s/application.version:.*/application.version:$EMBY_VERSION/g" app.properties
      - name: Check if app.properties has changed
        run: |
          EXIT_CODE=0
          git diff --exit-code app.properties || EXIT_CODE=$?
          echo $EXIT_CODE
           # Set environment variable
          echo "EXIT_CODE=$EXIT_CODE" >> $GITHUB_ENV
      - name: Install Groovy
        if: ${{ env.EXIT_CODE == 1 }}
        uses: WtfJoke/setup-groovy@v1
        with: 
          groovy-version: "4.x"
      - name: Regenerate repository.xml
        if: ${{ env.EXIT_CODE == 1 }}
        run: groovy createRepository.groovy
      - name: Commit + push changes
        if: ${{ env.EXIT_CODE == 1 }}
        run: |
          git config --local user.name "Octocat"
          git config --local user.email 'octocat@users.noreply.github.com'
          git add repository.xml
          git add app.properties
          git commit -m "⬆️ Update Emby to $EMBY_VERSION"
          git push
