name: "CI"
on:
  pull_request:
  push:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Install SDKMAN + Groovy
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          # Install a latest version of groovy
          sdk install groovy
      - uses: actions/checkout@v3
      - name: Regenerate repository.xml
        run: | 
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          groovy createRepository.groovy
      - name: Check if repository.xml has changed
        run: |
          EXIT_CODE=0
          git diff --exit-code repository.xml || EXIT_CODE=$?
           # Set environment variable
          echo "EXIT_CODE=$EXIT_CODE" >> $GITHUB_ENV
      - name: Commit + push changes
        if: ${{ env.EXIT_CODE == 1 }}
        run: |
          git config --local user.name "Octocat"
          git config --local user.email 'octocat@users.noreply.github.com'
          git add repository.xml
          git commit -m "📦 Regenerate repository.xml"
          git push